on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: moto-academy-web
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker authentication
      run: gcloud auth configure-docker gcr.io

    - name: Build and push Docker image
      env:
        IMAGE_NAME: gcr.io/moto-academy-web/node-cloud-sql
        TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

    - name: Deploy to Cloud Run
      env:
        IMAGE_NAME: gcr.io/moto-academy-web/node-cloud-sql
        TAG: ${{ github.sha }}
      run: |
        gcloud run deploy node-cloud-sql \
          --image $IMAGE_NAME:$TAG \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
